### ISSUE TITLE
No module named Slippage

### ISSUE THREAD

**Issue by malhotrachetan** [philipodonnell/paperbroker#8]
File ".../lib/python3.6/site-packages/pyalgotrade/broker/fillstrategy.py", line 25, in <module>
    import slippage

**Comment by philipodonnell** [comment]
Hello. I'm not aware of a dependency on `pyalgotrade`, can you illustrate where you found this error? From my googling it appears that `pyalgotrade` doesn't support Python3, so if you're trying to mix and match it may not work.
